import type UserProfile from "@/constants/UserProfile"

const Users: Array<UserProfile> = [
  {
    username: "Mike_330",
    password: "password",
    email: "john.doe@gmail.com",
    settings: {
        username: "Mike_330",
        age: 32,
        bio: "Hi there!",
        weeklyGoal: 4,
        shareData: true,
    },
    showcaseAchievements: [],
    personalGoals: [],
    weeklyFrequency: 4,
    weeklyConsistencyStreak: 16,
    status: 2,
  },
    {
    username: "WilliamPT",
    password: "password",
    email: "john.doe@gmail.com",
    settings: {
        username: "WilliamPT",
        age: 28,
        bio: "Hi there!",
        weeklyGoal: 2,
        shareData: true,
    },
    showcaseAchievements: [],
    personalGoals: [],
    weeklyFrequency: 1,
    weeklyConsistencyStreak: 6,
    status: 1,
  },
    {
    username: "Sarah.B",
    password: "password",
    email: "john.doe@gmail.com",
    settings: {
        username: "Sarah.B",
        age: 32,
        bio: "Hi there!",
        weeklyGoal: 1,
        shareData: true,
    },
    showcaseAchievements: [],
    personalGoals: [],
    weeklyConsistencyStreak: 3,
    weeklyFrequency: 1,
    status: 0,
  },
    {
    username: "BillyJones",
    password: "password",
    email: "john.doe@gmail.com",
    settings: {
        username: "BillyJones",
        age: 23,
        bio: "Hi there!",
        weeklyGoal: 2,
        shareData: true,
    },
    showcaseAchievements: [],
    personalGoals: [],
    weeklyFrequency: 1,
    weeklyConsistencyStreak: 22,
    status: 2,
  },
    {
    username: "sammy_02",
    password: "password",
    email: "john.doe@gmail.com",
    settings: {
        username: "sammy_02",
        age: 24,
        bio: "Hi there!",
        weeklyGoal: 4,
        shareData: true,
    },
    showcaseAchievements: [],
    personalGoals: [],
    weeklyFrequency: 3,
    weeklyConsistencyStreak: 9,
    status: 2,
  },
    {
    username: "GregBlake",
    password: "password",
    email: "john.doe@gmail.com",
    settings: {
        username: "GregBlake",
        age: 31,
        bio: "Hi there!",
        weeklyGoal: 2,
        shareData: true,
    },
    showcaseAchievements: [],
    personalGoals: [],
    weeklyFrequency: 1,
    weeklyConsistencyStreak: 1,
    status: 0,
  },
    {
    username: "jayJo.K",
    password: "password",
    email: "john.doe@gmail.com",
    settings: {
        username: "jayJo.K",
        age: 21,
        bio: "Hi there!",
        weeklyGoal: 1,
        shareData: true,
    },
    showcaseAchievements: [],
    personalGoals: [],
    weeklyFrequency: 1,
    weeklyConsistencyStreak: 12,
    status: 2,
  },
    {
    username: "mikeyB",
    password: "password",
    email: "john.doe@gmail.com",
    settings: {
        username: "mikeyB",
        age: 24,
        bio: "Hi there!",
        weeklyGoal: 3,
        shareData: true,
    },
    showcaseAchievements: [],
    personalGoals: [],
    weeklyFrequency: 2,
    weeklyConsistencyStreak: 15,
    status: 2,
  },
  {
    username: "lianne_22",
    password: "password",
    email: "john.doe@gmail.com",
    settings: {
        username: "lianne_22",
        age: 24,
        bio: "Hi there!",
        weeklyGoal: 3,
        shareData: true,
    },
    showcaseAchievements: [],
    personalGoals: [],
    weeklyFrequency: 2,
    weeklyConsistencyStreak: 7,
    status: 1,
  },
];

export default Users;